language: php

php:
  - 5.6
  - 7.0
  - 7.1
  - 7.2

install:
  - travis_retry composer self-update
  - travis_retry composer install --no-interaction --no-suggest

before_script:
  - composer require --dev satooshi/php-coveralls
  - "curl -H 'Cache-Control: no-cache' https://raw.githubusercontent.com/fossas/fossa-cli/master/install.sh | sudo bash"

script:
  - ./vendor/bin/phpunit --coverage-clover ./tests/logs/clover.xml

after_script:
  - php vendor/bin/coveralls -v
